<?php
$data = array (
  466 => 
  array (
    'cat_id' => '466',
    'cat_name' => '车型分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '466',
    'name' => '车型分类',
  ),
  467 => 
  array (
    'cat_id' => '467',
    'cat_name' => '小型汽车',
    'measure_unit' => '',
    'parent_id' => '466',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '467',
    'name' => '小型汽车',
  ),
  468 => 
  array (
    'cat_id' => '468',
    'cat_name' => '卡车及工程车',
    'measure_unit' => '',
    'parent_id' => '466',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '468',
    'name' => '卡车及工程车',
  ),
  476 => 
  array (
    'cat_id' => '476',
    'cat_name' => '天然汽车油品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '476',
    'name' => '天然汽车油品',
  ),
  479 => 
  array (
    'cat_id' => '479',
    'cat_name' => '10W-40',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '479',
    'name' => '10W-40',
  ),
  480 => 
  array (
    'cat_id' => '480',
    'cat_name' => '15W-40',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '480',
    'name' => '15W-40',
  ),
  477 => 
  array (
    'cat_id' => '477',
    'cat_name' => '5W-30',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '477',
    'name' => '5W-30',
  ),
  478 => 
  array (
    'cat_id' => '478',
    'cat_name' => '20W-50',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '478',
    'name' => '20W-50',
  ),
  481 => 
  array (
    'cat_id' => '481',
    'cat_name' => '汽油车油品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '481',
    'name' => '汽油车油品',
  ),
  482 => 
  array (
    'cat_id' => '482',
    'cat_name' => '5W-40',
    'measure_unit' => '',
    'parent_id' => '481',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 1,
    'id' => '482',
    'name' => '5W-40',
  ),
  486 => 
  array (
    'cat_id' => '486',
    'cat_name' => '0W-40',
    'measure_unit' => '',
    'parent_id' => '481',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '486',
    'name' => '0W-40',
  ),
  483 => 
  array (
    'cat_id' => '483',
    'cat_name' => '15W-40',
    'measure_unit' => '',
    'parent_id' => '481',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '483',
    'name' => '15W-40',
  ),
  484 => 
  array (
    'cat_id' => '484',
    'cat_name' => '5W-30',
    'measure_unit' => '',
    'parent_id' => '481',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '484',
    'name' => '5W-30',
  ),
  485 => 
  array (
    'cat_id' => '485',
    'cat_name' => '20W-50',
    'measure_unit' => '',
    'parent_id' => '481',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '485',
    'name' => '20W-50',
  ),
  469 => 
  array (
    'cat_id' => '469',
    'cat_name' => '柴油车油品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '469',
    'name' => '柴油车油品',
  ),
  473 => 
  array (
    'cat_id' => '473',
    'cat_name' => '0W-40',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '473',
    'name' => '0W-40',
  ),
  470 => 
  array (
    'cat_id' => '470',
    'cat_name' => '20W-50',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '470',
    'name' => '20W-50',
  ),
  474 => 
  array (
    'cat_id' => '474',
    'cat_name' => '5W-40',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '474',
    'name' => '5W-40',
  ),
  471 => 
  array (
    'cat_id' => '471',
    'cat_name' => '5W-30',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '471',
    'name' => '5W-30',
  ),
  475 => 
  array (
    'cat_id' => '475',
    'cat_name' => '10W-40',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '475',
    'name' => '10W-40',
  ),
  472 => 
  array (
    'cat_id' => '472',
    'cat_name' => '15W-40',
    'measure_unit' => '',
    'parent_id' => '469',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '472',
    'name' => '15W-40',
  ),
);
?>